---
title: "dbRDA_Analysis"
output: html_document
date: "2024-11-07"
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
dev.off()
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_knit$set(root.dir = "/Users/alex/Documents/Documents - Alex’s MacBook Pro/Documents/GitHub/Aus-Invasions-2023-Course")
```

#Set WD
```{r}
setwd("/Users/alex/Documents/Documents - Alex’s MacBook Pro/Documents/GitHub/Aus-Invasions-2023-Course")
```

#Load libararies
```{r}
library(tidyverse)
library(vegan)
library(dplyr)
library(readxl)
```

#Reading in distance matrices & metadata
```{r}
#Includes all root & soil samples
AMF = read.csv("Aus23_18S_Metabarcoding/OTUTables/Aitchison_pooled_18S.csv")
Bac = read.csv("Aus23_16S_Metabarcoding/OTUTables/Aitchison_pooled_rel_16S.csv")
Fung = read.csv("Aus23_ITS_Metabarcoding/OTUTables/Aitchison_pooled_ITS.csv")

#Removing negative controls
Bac = Bac[-19,-20]
Fung = Fung[-19,-20]

#Read in metadata
Meta = read_excel("/Users/alex/Documents/Documents - Alex’s MacBook Pro/Documents/GitHub/Aus-Invasions-2023-Course/Aus23_allData_11Nov24.csv.xlsx")

#Removing root samples from each df
Bac = Bac[-c(1,3,5,7,9,11,13,15,17,19,21,23,25,27,29,31,33,35),]
Bac = Bac[,-c(2,4,6,8,10,12,14,16,18,20,22,24,26,28,30,32,34,36)]
Fung = Fung[-c(1,3,5,7,9,11,13,15,17,19,21,23,25,27,29,31,33,35),]
Fung = Fung[,-c(2,4,6,8,10,12,14,16,18,20,22,24,26,28,30,32,34,36)]
AMF = AMF[-c(1,3,5,7,9,11,13,15,17,19,21,23,25,27,29,31,33,35),]
```

#Bacteria dbRDA
```{r}
#Begin dbRDA
#Change first column to rownames
Bac = Bac %>% remove_rownames %>% column_to_rownames(var="X")
x = Bac
x_meta = Meta
bac_dbrda = vegan::dbrda(x~ perc_N + perc_C + CN_ratio + ergosterol + tot_P + perc_P + soil_moisture + organic_matter_LOI + dbh_cm + height_m + litter_depth + pine_litter_prop + euc_litter_prop + total_litter_biomass, data=x_meta)
print(bac_dbrda)
summary(bac_dbrda)
plot(bac_dbrda)
```

#Fungi dbRDA
```{r}
#Change first column to rownames
Fung = Fung %>% remove_rownames %>% column_to_rownames(var="X")
x = Fung
x_meta = Meta
fung_dbrda = vegan::dbrda(x~ perc_N + perc_C + CN_ratio + ergosterol + tot_P + perc_P + soil_moisture + organic_matter_LOI + dbh_cm + height_m + litter_depth + pine_litter_prop + euc_litter_prop + total_litter_biomass, data=x_meta)
print(fung_dbrda)
summary(fung_dbrda)
plot(fung_dbrda)
```

#AMF dbRDA
```{r}
#Change first column to rownames
AMF = AMF %>% remove_rownames %>% column_to_rownames(var="X")
x = AMF
x_meta = Meta
amf_dbrda = vegan::dbrda(x~ perc_N + perc_C + CN_ratio + ergosterol + tot_P + perc_P + soil_moisture + organic_matter_LOI + dbh_cm + height_m + litter_depth + pine_litter_prop + euc_litter_prop + total_litter_biomass, data=x_meta)
print(amf_dbrda)
summary(amf_dbrda)
plot(amf_dbrda)
```

