library(tidyverse)

OtuMatITS_rare_pooled=
  read_delim("../Aus23_ITS_Metabarcoding/OTUTables/OtuMatITS_rare_pooled.csv", delim=",") %>%
  column_to_rownames(var = colnames(.)[1])

DSE_List=read_excel("../Aus23_ITS_Metabarcoding/DSE_List.xlsx")

#reads in custom list of specific OTUs that have
#been identified as likely DSEs (and which were
#not on DSE_List of known DSE genera)
#this was generated by reviewing top 100 most
#abundant fungi and BLASTing when needed
DSE_otus=
  c("dc1054a38cbcc63bc2818262e6f31d7c",
    "ad55e0ff7a0a3ca44b034e6f7a50519e",
    "1b3753029acde9bf8c79555f4589fcb0")

TaxITS_funguild=
  read.delim("../Aus23_ITS_Metabarcoding/ITS2_Dada2_repseqs97_taxonomy_edited_FunT_FunG.tsv") %>% 
  select(-c(Sequence, Kingdom, NeedToCheck, HaveChecked, Edited, Species, SpeciesHypothesis, Confidence)) %>%
  rename("otu"="Feature.ID")

TaxITS_funguild_edit=
  TaxITS_funguild %>%
  select(otu, primary_lifestyle) %>%
  left_join(TaxMatITS) %>%
  mutate(guild_edit=case_when(
    Genus %in% DSE_List$Taxon ~ "Dark Septate Endophyte",
    Family %in% DSE_List$Taxon ~ "Dark Septate Endophyte",
    otu %in% DSE_otus ~ "Dark Septate Endophyte",
    Genus=="Suillus" ~ "Suillus",
    Genus=="Rhizopogon" ~ "Rhizopogon",
    primary_lifestyle=="ectomycorrhizal" ~ "Other ECM",
    str_detect(primary_lifestyle, regex("saprotroph", ignore_case = TRUE)) ~ "Saprotroph",
    .default="Other"
  ))

GuildSummary=
  OtuMatITS_rare_pooled_rel %>%
  mutate(TreeSampleType=rownames(.)) %>%
  gather("otu", "abundance", -TreeSampleType) %>%
  left_join(TaxITS_funguild_edit) %>% 
  group_by(guild_edit, TreeSampleType) %>%
    summarise(abundance=sum(abundance)) %>%
  left_join(Metadata_ITS_pooled) %>%
  mutate(guild_edit =
           factor(guild_edit, 
                  levels=c(
                    "Other",
                    "Saprotroph",
                    "Dark Septate Endophyte",
                    "Other ECM",
                    "Rhizopogon",
                    "Suillus"
                  )))

guild_colors <- c(
  "Suillus" = "slateblue4",
  "Rhizopogon" = "slateblue1",
  "Dark Septate Endophyte" = "orangered3",
  "Other ECM" = "springgreen4",
  "Saprotroph" = "grey65",
  "Other"="grey65"
)

ggplot(GuildSummary, 
       aes(x=TreeSampleType, y=abundance, fill=guild_edit)) +
  geom_bar(stat="identity") +
  scale_fill_manual(values = guild_colors)  +
  theme_test() +
  theme(axis.text.x = element_blank(),   # Removes x-axis text
        axis.ticks.x = element_blank(),
        axis.title.x = element_blank()) +
  ylab("Relative Abundance") +
  labs(fill = "Fungal Guild") +
  scale_y_continuous(limits = c(0,1.02), expand = c(0, 0)) +
  facet_grid(.~TreeSpecies_SampleType, scales="free")

