---
title: "dbRDA_ComMatrices"
output: html_document
date: "2024-12-31"
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_knit$set(root.dir = "/Users/alex/Documents/Documents - Alex’s MacBook Pro/Documents/GitHub/Aus-Invasions-2023-Course")
```

#Set WD
```{r}
setwd("/Users/alex/Documents/Documents - Alex’s MacBook Pro/Documents/GitHub/Aus-Invasions-2023-Course/dbRDA")
```

#Load libararies
```{r}
library(tidyverse)
library(vegan)
library(dplyr)
library(readxl)
```

#Reading in distance matrices & metadata
```{r}
#Includes all root & soil samples
#Community matrices by sample name
Bac = read.csv("/Users/alex/Documents/Documents - Alex’s MacBook Pro/Documents/GitHub/Aus-Invasions-2023-Course/dbRDA/OtuMat16S_pooled_rel.csv")
Fung = read.csv("/Users/alex/Documents/Documents - Alex’s MacBook Pro/Documents/GitHub/Aus-Invasions-2023-Course/dbRDA/OtuMatITS_pooled_rel.csv")
AMF = read.csv("/Users/alex/Documents/Documents - Alex’s MacBook Pro/Documents/GitHub/Aus-Invasions-2023-Course/dbRDA/OtuMat18S_pooled_rel.csv")

#Remove negative controls
Fung = Fung[-19,]
Bac = Bac[-19,]

#Removing root samples
AMF = AMF[-c(1,3,5,7,9,11,13,15,17,19,21,23,25,27,29,31,33,35),]
Fung = Fung[-c(1,3,5,7,9,11,13,15,17,19,21,23,25,27,29,31,33,35),]
Bac = Bac[-c(1,3,5,7,9,11,13,15,17,19,21,23,25,27,29,31,33,35),]

#Read in metadata
Meta = read.csv("/Users/alex/Documents/Documents - Alex’s MacBook Pro/Documents/GitHub/Aus-Invasions-2023-Course/Merged_data/Aus23_allData_19Nov24.csv")
```

#Bacteria dbRDA w/ capscale
```{r}
#First column to rownames
Bac = Bac %>% remove_rownames %>% column_to_rownames(var="X")
#Formula
dbrda_bac = capscale(formula = Bac ~ perc_N + perc_C + ergosterol + perc_P + soil_moisture + organic_matter_LOI + dbh_cm + height_m + litter_depth + pine_litter_prop + euc_litter_prop + total_litter_biomass, data=Meta, distance = "robust.aitchison", sqrt.dist=TRUE)
print(dbrda_bac)
#Including these variables below lead to overfitting
#Litter_OLayer_ergosterol, Litter_OLayer_percP, Litter_OLayer_percN, Litter_OLayer_percC, Litter_avg_ergosterol
#Removed these for likely collinearity
#CN_ratio
#Pine litter and Euc litter prop are negatively correlated but are important predictors

#Create summary
dbrda_bac_sum = summary(dbrda_bac)
print(dbrda_bac_sum)
dbrda_bac_sum$biplot

#ANOVA
anova(dbrda_bac, by="margin")
#No significant predictors

#Plotting
plot(dbrda_bac)

#Pulling species scores
scores(dbrda_bac)
```

#Fungi dbrda w/ capscale
```{r}
#First column to rownames
Fung = Fung %>% remove_rownames %>% column_to_rownames(var="X")
#Formula
dbrda_fung = capscale(formula = Fung ~ perc_N + perc_C + ergosterol + perc_P + soil_moisture + organic_matter_LOI + dbh_cm + height_m + litter_depth + pine_litter_prop + euc_litter_prop + total_litter_biomass, data=Meta, distance = "robust.aitchison", sqrt.dist=TRUE)
print(dbrda_fung)
#Including these variables below leads to overfitting
#Litter_OLayer_ergosterol, Litter_OLayer_percP, Litter_OLayer_percN, Litter_OLayer_percC, Litter_avg_ergosterol
#Removed these for likely collinearity
#CN_ratio
#Pine litter and Euc litter prop are negatively correlated but are important predictors

#Create summary
dbrda_fung_sum = summary(dbrda_fung)
print(dbrda_fung_sum)
dbrda_fung_sum$biplot

#ANOVA
anova(dbrda_fung, by="margin")
#No significant predictors

#Plotting
plot(dbrda_fung)

#Pulling species scores
scores(dbrda_fung)
```

#AMF dbrda w/ capscale
```{r}
#First column to rownames
AMF = AMF %>% remove_rownames %>% column_to_rownames(var="X")
#Formula
dbrda_amf = capscale(formula = AMF ~ perc_N + perc_C + ergosterol + perc_P + soil_moisture + organic_matter_LOI + dbh_cm + height_m + litter_depth + pine_litter_prop + euc_litter_prop + total_litter_biomass, data=Meta, distance = "robust.aitchison", sqrt.dist=TRUE)
print(dbrda_amf)
#Including these variables below leads to overfitting
#Litter_OLayer_ergosterol, Litter_OLayer_percP, Litter_OLayer_percN, Litter_OLayer_percC, Litter_avg_ergosterol
#Removed these below for likely collinearity
#CN_ratio
#Pine litter and Euc litter prop are negatively correlated but are important predictors

#Create summary
dbrda_amf_sum = summary(dbrda_amf)
print(dbrda_amf_sum)
dbrda_amf_sum$biplot

#ANOVA
anova(dbrda_amf, by="margin")
#No significant predictors

#Plotting
plot(dbrda_amf)

#Pulling species scores
scores(dbrda_amf)
```

